locals {
  blueprint = yamldecode(file("${path.module}/../../../render.yaml"))

  matching_services = [
    for service in try(local.blueprint.services, []) : service
    if try(service.type, "") == "web" && try(service.name, "") == var.service_name
  ]

  service  = try(local.matching_services[0], {})
  env_vars = { for env_var in try(local.service.envVars, []) : env_var.key => env_var }
}

check "render_blueprint_free_demo" {
  assert {
    condition     = length(local.matching_services) == 1
    error_message = "render.yaml must define exactly one web service named ${var.service_name}."
  }

  assert {
    condition     = try(local.service.runtime, "") == "docker"
    error_message = "${var.service_name} must use Render's docker runtime."
  }

  assert {
    condition     = try(local.service.plan, "") == "free"
    error_message = "${var.service_name} must stay on Render's free plan for the portfolio demo."
  }

  assert {
    condition     = try(local.service.healthCheckPath, "") == "/up"
    error_message = "${var.service_name} must use /up as the health check path."
  }

  assert {
    condition     = try(local.env_vars.DATABASE_URL.sync, true) == false
    error_message = "DATABASE_URL must be configured outside the repository."
  }

  assert {
    condition     = try(local.env_vars.SECRET_KEY_BASE.generateValue, false) == true
    error_message = "SECRET_KEY_BASE must be generated by Render."
  }
}
